# rename to config.toml

[mqtt]
enabled = true
host = "192.168.10.100"
port = 1883
client_id = "indra_client"
username = "your-username"
password = "your-password"

topic = "indra/monitor"				# Publish data
interval = 10                			# seconds

sub = "indra/cmd_sub"				#Receive commands

mqtt_smart_charge_topic = "indra_from_ha/smartcharge/status"			#Will charge if supplier offers dynamic off-peak rates e.g Octopus Intelligent Tariffs. (if value = 1 )
mqtt_smart_charge_field = "smartcharge"

mqtt_ev_drain_protection_topic = "indra_from_ha/evdrainprotection/status"	#Will prevent discharge when EV is charging (if value = 1 )
mqtt_ev_drain_protection_field = "evdrainprotection"

mqtt_timeout_seconds = 120      						# 2 minutes - if no update, treat meter as offline



[meter]
meter_type = "mqtt"								# modbus(default) or mqtt 
address = "your-rtu-over-tcp-meter-address:port"

mqtt_meter_host = "192.168.10.100"
mqtt_meter_port = 1883
mqtt_meter_client_id = "indra_meter_client"
mqtt_meter_username = "your-username"
mqtt_meter_password = "your-password"

mqtt_meter_total_power_topic = "glow/30C6F759930C/SENSOR/electricitymeter"	#e.g. { "power": 995, "powerl1": 186, "powerl2": 409, "powerl3": 400, "timestamp": 1776211377 }
mqtt_meter_total_power_field = "electricitymeter.power.value"			#the field to extract from the JSON(unused if single value publisheda) blank
mqtt_meter_total_power_scale = 1000.0 						#multiplication factor to watts - If meter provides kw then use 1000

mqtt_meter_phase_power_topic = "indra_from_ha/grid/status"			#Only required for 3 phase to limit export 
mqtt_meter_phase_power_field = "powerl3"
mqtt_meter_phase_power_scale = 1

mqtt_meter_timeout_seconds = 120      						# 2 minutes - if no update, treat meter as offline

