alias: Publish Smart EV Drain Protection → mbmd MQTT
description: Send Zappi + Eddi Power Readings as clean JSON
triggers:
  - trigger: state
    entity_id:
      - sensor.myenergi_zappi_22323585_internal_load_ct1
      - sensor.myenergi_eddi_24456595_internal_load_ct1
    for:
      seconds: 1
  - trigger: time_pattern
    seconds: /30
actions:
  - action: mqtt.publish
    data:
      topic: indra_from_ha/ev_drain_protection/request
      qos: 0
      retain: true
      payload: |-
        {
          "ev_drain_protection": {{ 1 if (states('sensor.myenergi_zappi_22323585_internal_load_ct1') | float(0) > 0 or states('sensor.myenergi_eddi_24456595_internal_load_ct1') | float(0) > 0) else 0 }},
          "zappi_power": {{ states('sensor.myenergi_zappi_22323585_internal_load_ct1') | float(0) | round(0) }},
          "eddi_power": {{ states('sensor.myenergi_eddi_24456595_internal_load_ct1') | float(0) | round(0) }}
        }
mode: single
